name: entries_api
description: The interface and models for an API providing access to journals.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.7.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  uuid: ^4.3.3

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  test: ^1.21.4